# Configuration for pre-commit hooks
# Install with: pip install pre-commit && pre-commit install

repos:
  # Built-in pre-commit hooks for basic checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: \.md$  # Allow trailing spaces in markdown for line breaks
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']  # Prevent files larger than 1MB


  # Python linting with flake8
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        args: [
          "--max-line-length=88",  # Match Black's line length
          "--extend-ignore=E203,W503",  # Ignore conflicts with Black
          "--exclude=migrations,__pycache__,.git,venv,.venv"
        ]
        files: \.py$

  # Your custom formatting script (BLOCKS commit on failure)
  - repo: local
    hooks:
      - id: custom-formatting
        name: Custom Python Formatting Check
        entry: python3
        args: [src/gambitpairing/resources/scripts/formatting.py, --target, src/gambitpairing, --check]
        language: system
        files: \.py$
        pass_filenames: false  # Don't pass individual filenames to the script

  # TODO comment check (WARNING only - doesn't block commit)
  - repo: local
    hooks:
      - id: todo-warning
        name: TODO Comment Warning
        entry: bash
        args: [-c, 'files=$(git diff --cached --name-only --diff-filter=AM | grep -E "\.(py|js|ts|java|cpp|c|h|go|rs)$"); if [ -n "$files" ]; then echo "$files" | xargs grep -Hn "TODO" || echo "✅ No TODOs found"; else echo "✅ No code files staged"; fi']
        language: system
        always_run: false
        verbose: true
        # NOTE: No 'fail_fast: true' means this won't block the commit

  # Type checking with mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
      - id: mypy
        files: \.py$
        args: [--ignore-missing-imports, --no-strict-optional]
        additional_dependencies: [types-requests]  # Add type stubs as needed


# Global configuration
default_language_version:
  python: python3

# Speed up hooks by only running on changed files
default_stages: [pre-commit]

# Fail fast - stop on first failure
fail_fast: false  # Set to true if you want to stop on first error
